apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: argocd-server-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argocd-server
            port: 
              number: 80
